version: '3'
#volumes:
#  postgres_session_data:
#    driver: local
#  postgres_keycloak_data:
#    driver: local
services:
  #  session-postgres:
  #    image: postgres
  #    volumes:
  ##      - postgres_session_data:/var/lib/postgresql/data
  #    environment:
  #      POSTGRES_DB: session
  #      POSTGRES_USER: gateway
  #      POSTGRES_PASSWORD: password
  #    ports:
  #      - '15432:5432'
  redis:
    image: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    ports:
      - '6379:6379'
  postgres:
    image: postgres:16
#    volumes:
      #      - postgres_keycloak_data:/var/lib/postgresql/data
#      - ./postgres-session/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - '15432:5432'
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm --db postgres --db-url-host postgres --db-username keycloak --db-password password
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
    #JDBC_PARAMS: "ssl=true"
    ports:
      - 8090:8080
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      - postgres
#  membrane:
#    image: predic8/membrane
#    restart: always
#    ports:
#      - 2000:2000
#      - 3000:3000
#      - 9001:9001
#    volumes:
#      - ./membrane/proxies.xml:/opt/membrane/conf/proxies.xml
#    depends_on:
#      - keycloak